FROM python

RUN apt-get update && apt-get install git libbz2-dev -y
COPY ./../pipeline_requirements.txt /srv/pipeline_requirements.txt
RUN python3 -m pip install -r /srv/pipeline_requirements.txt

WORKDIR /srv/scripts
